### ISSUE TITLE
cookie clicker

### ISSUE THREAD

**Issue by theclickerofcookies** [Stormyskitten/CookieClickerUnblocked#3]
when i place a worship on the Daimond tad it doesn't stay there

**Comment by Stormyskitten** [comment]
Apologies for the late response. I have only just seen this. I cant seem to recreate this issue. When it disappears is it after a browser refresh or game load? Also what spirit are you placing there, as if you are placing Holobore the spirit gets unslotted when a golden cookie gets clicked.
